{% set name = "traja" %}
{% set version = "0.0.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/justinshenk/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 117bf9bad06264004ede49215d8bb3c4c38e0812abfef8e08ffd316ee2ebc22c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pandas
    - matplotlib
    - numpy
    - scipy
    - seaborn
    - shapely
    - pillow
    - fastdtw
    - ipython

test:
  imports:
    - traja

about:
  home: https://github.com/justinshenk/traja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Traja is a Python library for trajectory analysis and visualization
  doc_url: https://traja.readthedocs.io 
  dev_url: https://github.com/justinshenk/traja 

extra:
  recipe-maintainers:
    - justinshenk
