{% set name = "traja" %}
{% set version = "0.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04b9c206e4170dd3d4f1bb91083600867dd5a58be62e125e2ce657b6428b4087

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pandas
    - matplotlib
    - numpy
    - scipy
    - seaborn
    - shapely
    - pillow
    - fastdtw
    - ipython

test:
  imports:
    - traja

about:
  home: https://github.com/justinshenk/traja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Traja is a Python library for trajectory analysis and visualization
  doc_url: https://traja.readthedocs.io 
  dev_url: https://github.com/justinshenk/traja 

extra:
  recipe-maintainers:
    - justinshenk
