{% set name = "traja" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/justinshenk/traja/archive/v{{ version }}.tar.gz
  sha256: a15897508941df2ef433394dad108f37c2227057a9617ee349d9a0862eb4a7bb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pandas
    - matplotlib
    - numpy
    - scipy
    - seaborn
    - shapely
    - pillow
    - fastdtw
    - ipython

test:
  imports:
    - traja

about:
  home: https://github.com/justinshenk/traja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Traja is a Python library for trajectory analysis and visualization
  doc_url: https://traja.readthedocs.io 
  dev_url: https://github.com/justinshenk/traja 

extra:
  recipe-maintainers:
    - justinshenk
