travis:
  secure:
    BINSTAR_TOKEN: WGBPzq2UhN1QjiNlw6/BrsmyV3Vz4GNufvKqTWce6+3msPK+zGdKK6Ch9CXMNPi0sWr2TlEEKQ5qnc1VGi2bK3/BiXQK1mIbV5jvcqwwmQaL+vmmgl/0uHvuXWM7hqYdMrppfBZiTWerioGjCeVIxbosW03kjTC4f9ngFXUiipzGAYt6MYKZhRYrev/6ouzuGbTGsgaE53jCO1QMHArIzJ4DhrDX+lRv/MYI/FL9Iqd7VqdBmg1wnZg1gsYHB+uYOtkSC+/VpEuA/xiCWRi7UkUXZBnCUx2liMM1FdQoScQPtaQZ5YNLa+Bwyf/qLrXlvZ5BIUlqjfk4Z1CIWR+/SA3xPs8wZMpQBVwL2tEU8wmbP5NaV/dSkIfGt1vgWY1VEZq5ylpyL9nLiAZ/zbigrCp/BBt72D3jwAlA1DznWRcL20KeNGnbQP0HwqIH1/bLPPJGxQsbpKm47M1pexzfbVSM1BoOgwpP+MRqG5yr+PJpOhr8/uYpyfnvvUmCHf+kTHhCiFpUTOrICeRfq18sEUaFwprAOc/s/BK2diGPpKqPZgXVn55AoRR7yiUksdgf6GBgH6Fg3G6rpeW+/XS5NbYijd9HTn+Yr+W4yLCBY+NpmCpUj+OK3yZVbKet9LS83YfCVmh3k1MtVOGHpeFFEip6VRXTXaY4I4QMYekygRk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
